robot:
  model: "myCobot320PI"
  mode: "mock"
  port: "/dev/ttyAMA0"
  baudrate: 1000000
  default_speed: 35
  handover_coords: [80.0, -220.0, 180.0, 0.0, 0.0, 0.0]
  gripper:
    open_value: 80
    close_value: 20
  camera:
    sdk_path: "D:\\Documnet\\Other material\\3D摄像头客户资料\\驱动程序及SDK开发\\windows\\OpenNI2 SDK\\Windows_V2.3.0\\windows\\SDK\\x64\\Redist"
    calibration_img_dir: "D:\\camera_images"
    chessboard_size: [9, 6]
    square_size: 0.025